export const CREATE_PATIENT = "CREATE_PATIENT";
export const GET_PATIENT = "GET_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const SELECT_PATIENT = "SELECT_PATIENT";
export const CLEAR_PATIENT = "CLEAR_PATIENT";
export const DELETE_SELECTED_PATIENT= "DELETE_SELECTED_PATIENT";
